### ISSUE TITLE
missing contents for build_pool_type migration scripts

### ISSUE THREAD

**Issue by PaulCharlton** [rocky-linux/peridot#100]
### Describe The Bug

https://github.com/rocky-linux/peridot/blob/main/peridot/migrate/20230217215146_add_build_pool_type_to_projects.down.sql 

and

https://github.com/rocky-linux/peridot/blob/main/peridot/migrate/20230217215146_add_build_pool_type_to_projects.up.sql

are empty files

### Reproduction Steps

view commit history at commit:  fe05de365aa1702e20e94bc61c6b7faa1b1f82e2

### Expected Behavior

migration scripts should not be empty

### Version and Build Information

latest at commit: fe05de365aa1702e20e94bc61c6b7faa1b1f82e2

**Comment by PaulCharlton** [comment]
WIP

**Comment by PaulCharlton** [comment]
PR submitted

**Comment by NeilHanlon** [comment]
Fixed by #101
