### ISSUE TITLE
bazel gazelle missing intermediate dependency on initial checkout

### ISSUE THREAD

**Issue by warthog9** [rocky-linux/peridot#106]
### Describe The Bug

This is half bug / half feature request.  It was observed that if you skip straight to the `bazel run //:gazelle` step of the build instructions bazel successfully completes and IMPLIES that it ran correctly, when it's clear that it's missing a build target / dependency needed to complete correctly.

This is a request to have an appropriate dependency check added to bazel to error correctly that the previous intermediate steps were not run and that bazel did in fact not fully build.

### Reproduction Steps

1. clone peridot
2. execute `bazel run //:gazelle`
3. claims successful build
. . .

### Expected Behavior

Errors as a previous intermediate dependency was missing that's created / setup in the previous steps

### Version and Build Information

git HEAD

**Comment by mstg** [comment]
Gazelle automatically creates BUILD files for the Go targets. It is not a build of any package, but rather automatically manages BUILD targets for us. https://github.com/bazelbuild/bazel-gazelle
