### ISSUE TITLE
user input not cleaned before passing to git

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/peridot#137]
https://github.com/rocky-linux/peridot/blob/95d7351c22059c8ab614799ee1e412967e514f78/peridot/builder/v1/workflow/sync.go#L802

we should not only strip() the string, but probably do a dumb check to make sure it looks something like a URI--to prevent blind fuzzing attacks

**Comment by MatthewHink** [comment]
net/url Parse maybe? If the parse succeeds it should be a valid url.

**Comment by mstg** [comment]
This is not necessary as we don't shell out to git, but use go-git which does a parsing on it's own
