### ISSUE TITLE
Support soft-delete projects

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/peridot#141]
### Is this feature request related to a problem? If so, please describe it.

sometimes we want to archive/delete projects, but we should attempt to _not_ actually delete them fully except when we really want to.

### Describe the solution you'd like to see

Add a column for the project state (deleted boolean), or a datetime column after which time a project is considered 'deleted'.

### Version and Build Information

n/a

**Comment by mstg** [comment]
Not planned for v1, v2 will most likely not keep the project concept so not sure it's worth to spend time on this.
