### ISSUE TITLE
[Question]What project/tool used in peridot for signing?

### ISSUE THREAD

**Issue by TommyLike** [rocky-linux/peridot#143]
### Describe The Bug

It's just a quesiton, what project&tool used in peridot for package signing? for example, obs-sign? rpm tool?

### Reproduction Steps

Not related

### Expected Behavior

Not related

### Version and Build Information

Not related

### Additional context

Not related

**Comment by mstg** [comment]
We're using [rpmsign](https://man7.org/linux/man-pages/man8/rpmsign.8.html) (https://github.com/rocky-linux/peridot/blob/main/peridot/keykeeper/v1/sign.go#L198)
