### ISSUE TITLE
Reference https://wiki.rockylinux.org/rocky/bugs/ in README.md

### ISSUE THREAD

**Issue by TrevorBenson** [rocky-linux/peridot#145]
### Is this feature request related to a problem? If so, please describe it.

N/A

### Describe the solution you'd like to see

Point the user to the wiki page for bugs inside README.md and suggest they read it prior to opening a bug in github.

### Version and Build Information

N/A

### Additional Context

Some users may start reviewing repositories at GitHub. As the wiki is its own separate repository it may not be found first when searching. Peridot does not have its own wiki tab. This can lead to opening issues in Peridot, and potentially other repositories, that may appear to be the correct location. However, with Bugzilla available is not where the issue is preferred to be submitted. 

Referencing this in the README.md may reduce the chance that an issue is opened against Peridot directly instead of as a bug in the Bugzilla instance.

**Comment by NeilHanlon** [comment]
Thank you!
