### ISSUE TITLE
RPM Import unable to process tarballs with multiple architectures

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/peridot#26]
### Describe The Bug

the builds/rpm-import path is unable to process tarballs containing multiple architectures' worth of RPMs with an error like 

```
RpmImportActivity Attempt 1 Error rpm: invalid file descriptor
```

### Reproduction Steps

1. Create a tarball with RPMs for at least two architectures
2. Submit a build request for this tarball once uploaded

### Expected Behavior

The import task completes or fails with an error describing that it cannot import multiple RPMs at a time. Ideally, we support multi-arch imports

### Version and Build Information

n/a

**Comment by mstg** [comment]
Since #61 we can reliably use `RpmBatchImport`. We should cease usage of the older tar import. I'm closing this as wontfix, and we will probably remove the old `RpmImport` soon anyways.
