### ISSUE TITLE
[BUG] Source RPM packages NEVRA and final binary packages do not fully match

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/peridot#27]
### Describe The Bug

During syncing, it was noticed that the binary packages have NEVRA's that generally match upstream but their source packages do *not* match, in particular, their dist tags. For example.

```
kernel-5.14.0-70.22.1.el9.src.rpm

kernel-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-abi-stablelists-5.14.0-70.22.1.el9_0.noarch.rpm
kernel-core-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-debug-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-debug-core-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-debug-modules-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-debug-modules-extra-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-modules-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-modules-extra-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-tools-5.14.0-70.22.1.el9_0.x86_64.rpm
kernel-tools-libs-5.14.0-70.22.1.el9_0.x86_64.rpm
```

When source packages are being built, their dist tags should match what they'll be producing.

**Note**: This does not affect the builds themselves as the correct dist tag tag is being passed to the mock build.

### Reproduction Steps

1. Build X package
2. Sync Y repository for any given architecture
3. Sync source repository
4. Verify the dist tags/NEVRA do not match

### Expected Behavior

The NEVRA/dist tags between the source packages and the binary built packages should match (eg if the import and build was for `el9_0` the binary *and* source package should both have `el9_0` in their dist)

### Version and Build Information

Current. This can be fixed before 9.1/8.7

### Additional context

This does not affect builds at all; it is simply an odd difference between the starting source package and the final built package.

**Comment by mstg** [comment]
This is currently caused by us not importing source rpms because source rpms, well doesn't have the same "Source RPM" as the rest of the RPMs. Source RPMs have empty values for that field. I propose that for the rpmimport workflow, we see if the RPM itself matches that field and allow an import to go through. This way we would be able to import the source rpms together with the other RPMs
