### ISSUE TITLE
RFE: Based on variants.xml from a pungi config, repos should not be available for some arches

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/peridot#3]
By default, all repositories are available regardless of architecture. Even if no packages are available (based on the pungi configuration and comps), the repository is still technically available and can be synced. This could potentially confuse users running empanadas to sync all repositories or mirror manager providing repositories with no content.

Priority is set to low as this isn't a breaking issue and is mostly aesthetic, and empanadas currently handles this case. There are also cases that this is occurring with pungi for Rocky Linux 8 as well, so this isn't a priority.

If we deem the current behavior is fine (on the surface it is), we can just close the issue.

**Comment by mstg** [comment]
We should be able to do this for hashed variants by checking if the primary package list empty before creating a variant for it. The repository would then fail with 404, if the compose toolkit can handle that scenario we can make the necessary changes in the coming days.

**Comment by nazunalika** [comment]
Doing this is likely not necessary. Repos are empty for specific repo/arch combinations, so it doesn't hurt that they end up existing. If it appears to be a larger issue later, we can reopen. (We have not had users file issues/bug reports on this sort of thing, and the repo combinations are outside of the normal ones like baseos, appstream, crb, and extras)
