### ISSUE TITLE
Peridot CLI - Allow admins to request package re-signs in the case a badly-signed RPM makes it through

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/peridot#37]
### Is this feature request related to a problem? If so, please describe it.

Sometimes Keykeeper--because it hates us--doesn't sign an RPM or signs it "improperly" such that subsequent reposyncs during compose fail due to improperly signed packages.

This requires an admin to go and request keykeeper resign the RPMs, and is currently a manual process that needs kubernetes administrator permissions.

### Describe the solution you'd like to see

Implement a command like

```
peridot project --project-id $PROJECT_ID resign-packages $PKGS...
```

That spawns a task to resign the named RPMs

### Have you considered alternative solutions/features? If so, please describe them.

Fix keykeeper.. Eventually this command will not be used very frequently and could be removed.

There are inherent security implications around opening up this API, but permissions are scoped such that these risks are mitigated at least mostly.

### Version and Build Information

n/a

**Comment by mstg** [comment]
#62 should hopefully fix this. Let's run it for a while and see, manual tests does seem to correctly error out at least.
