### ISSUE TITLE
[BUG] Catalog that excludes packages ignores noarch packages

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/peridot#72]
### Describe The Bug

When importing a catalog that excludes packages for certain architectures, the will be listed later. For example:

```
exclude_filter {
  repo_match: "^AppStream$"
  arch {
    key: "ppc64le"
    glob_match: "seavgabios-bin"
}

package {
  name: "seabios"
  type: PACKAGE_TYPE_NORMAL_FORK
  repository {
    name: "AppStream"
    include_filter: "seabios-bin.noarch"
    include_filter: "seabios.x86_64"
    include_filter: "seavgabios-bin.noarch"
  }
}
```

The only fix is to set a noarch package as the architecture, which is not the proper way to do it.

### Reproduction Steps

1. Exclude a package that is no arch from a repository
2. Import the catalog.
3. Package is still in the repository for that architecture.

### Expected Behavior

Packages that are noarch that are purposely excluded *should* be excluded.

### Version and Build Information

Current.

### Additional context

This is either a bug with the tooling that converts pungi data or with peridot itself.

**Comment by mstg** [comment]
This is a bug in yumrepofsupdater. There is a planned fix. For 9.1, let's use the workaround to get the catalog to the state we want, and when the fix is deployed we can revert to the catalog and re-process the affected builds again with correct behavior this time.

**Comment by mstg** [comment]
#71 should address this. Tests run for the last 9.1 sync does show success.
