### ISSUE TITLE
Apollo should be able to issue errata for Rocky Linux 9

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/peridot#82]
### Is this feature request related to a problem? If so, please describe it.

Apollo (previously secparse) issues advisories for Rocky Linux package updates which mirror RHEL advisories. Presently, the tool runs for only RL8, as it runs after the compose is complete. We are currently able to do this because RL8 is built in Koji and we are able to use Sigul to resign the repodata once we added the errata information (updateinfo).

With Peridot (and thus RL9 and soon RL8), we cannot use the same strategy because Keykeeper is unable to be invoked once packages leave Peridot. Put another way, the updateinfo must be included in the repositories exposed by yumrepofs BEFORE `empanadas` reposyncs and performs the compose process, since empanadas is unable to re-sign the repodata once it is exported from Peridot.

### Describe the solution you'd like to see

We should implement the ability for Apollo to run either during or after a build (perhaps during the repo hashing operation?).

It is necessary to have the errata information alongside the package repositories at the time of Compose by `empanadas`

### Version and Build Information

n/a

**Comment by mstg** [comment]
This has been possible for a while now.
